name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: server

env:
  NODE_VERSION: 16.x

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Lint Code
        shell: bash
        run: |
          yarn
          yarn eslint . --fix --ext .ts
          find . -name '*.json' -not -path './node_modules/*' -exec yarn jsonlint {} -q \;